export default {
	HEARTBEAT: "heartbeat",
	TEST: "test",
	LOGON_REQUEST: "logon",
	LOGON_COMPLETE: "logonAck",
	LOGOFF: "logoff",
	LOGOFF_COMPLETE: "logoffAck",
	PLACE_ORDER: "placeOrder",
	REPLACE_ORDER: "replaceOrder",
	CANCEL_ORDER: "cancelOrder",
	GET_ORDER_STATUS: "getOrderStatus",
	GET_ORDER_MASS_STATUS: "getOrderMassStatus",
	EXECUTION_REPORT: "executionReport",
	GET_ACCOUNT_DATA: "getAccountData",
	GET_ACCOUNT_BALANCES: "getAccountBalances",
    ACCOUNT_BALANCES_REPORT: "accountBalancesReport",
	ACCOUNT_DATA_REPORT: "accountDataReport",
    GET_OPEN_POSITIONS: "getOpenPositions",
	GET_WORKING_ORDERS: "getWorkingOrders",
	GET_COMPLETED_ORDERS: "getCompletedOrders",
	GET_EXCHANGE_PROPERTIES: "getExchangeProperties"
};
